trigger pipeline for testing

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -20,8 +20,8 @@ env:
 
 # Define Jobs
 jobs:
-  terraform:
-    name: "Deploy Infra with Terraform on AWS"
+  test:
+    name: "Testing Terraform Configuration"
     runs-on: ubuntu-latest
     # Run only on push events
     if: github.event_name == 'push'
@@ -33,14 +33,14 @@ jobs:
 
     steps:
       - name: Checkout source code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
+        uses: hashicorp/setup-terraform@v4
 
       - name: Terraform init
         id: init
-        run: terraform init -backend-config="bucket=$S3_BUCKET"
+        run: terraform init
 
       - name: Terraform validate
         id: validate
@@ -55,25 +55,67 @@ jobs:
         if: steps.plan.outcome == 'failure'
         run: exit 1
 
-      - name: Terraform apply
-        id: apply
-        run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+      - name: Check variables
+        id: check_vars
+        run: |
+          echo "ECR REPO '${{ vars.ecr_repo }}'"
+          echo "AWS REGION '${{ vars.aws_region }}'"
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ env.AWS_REGION }}
 
-      - name: Get Kubernetes config
-        id: getconfig
-        if: steps.apply.outcome == 'success'
-        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+  # terraform:
+  #   name: "Deploy Infra with Terraform on AWS"
+  #   runs-on: ubuntu-latest
+  #   # Run only on push events
+  #   if: github.event_name == 'push'
 
-      - name: Install Ingress controller
-        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
-        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
+  #   defaults:
+  #     run:
+  #       shell: bash
+  #       working-directory: ./terraform
+
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v6
+
+  #     - name: Setup Terraform
+  #       uses: hashicorp/setup-terraform@v4
+
+  #     - name: Terraform init
+  #       id: init
+  #       run: terraform init -backend-config="bucket=$S3_BUCKET"
+
+  #     - name: Terraform validate
+  #       id: validate
+  #       run: terraform validate
+
+  #     - name: Terraform plan
+  #       id: plan
+  #       run: terraform plan -no-color -input=false -out planfile
+  #       continue-on-error: true
+
+  #     - name: Terraform plan status
+  #       if: steps.plan.outcome == 'failure'
+  #       run: exit 1
+
+  #     - name: Terraform apply
+  #       id: apply
+  #       run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+  #     - name: Configure AWS credentials
+  #       uses: aws-actions/configure-aws-credentials@v6
+  #       with:
+  #         aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+  #         aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+  #         aws-region: ${{ env.AWS_REGION }}
+
+  #     - name: Get Kubernetes config
+  #       id: getconfig
+  #       if: steps.apply.outcome == 'success'
+  #       run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+
+  #     - name: Install Ingress controller
+  #       if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+  #       run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
 
   destroy:
     name: "Destroy Infra on AWS"
@@ -88,17 +130,17 @@ jobs:
 
     steps:
       - name: Checkout source code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
+        uses: hashicorp/setup-terraform@v4
 
       - name: Terraform init
         id: init
         run: terraform init -backend-config="bucket=$S3_BUCKET"
 
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
+        uses: aws-actions/configure-aws-credentials@v6
         with:
           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
